### PR TITLE
Remove failing package command from prerequisites, fix module names within part2/3/4

### PR DESCRIPTION
**Pull request by cunningt**
- The maven clean package command in prerequisites fails at the beginning because we haven't done the fixes to the routes in part-4 - I think it might be less confusing if that is removed from the setup
- fixed some label issues with part 2-6

### CODE REVIEW

**Comment by aldettinger** [comment]
Yeah, we may be able to keep mvn clean install but excluding the failing module.
The main idea is to predownload as much dependencies as possible.

About the labelling issue, we might fix this in another commit as it will be broken by another PR currently under review.

**Comment by cunningt** [comment]
Sounds good to me - feel free to close!

**Comment by zbendhiba** [comment]
@cunningt thanks for catching all problems in the Docker files.
I'll fix those today with the final renaming I've already pushed in the main branch.

**Comment by aldettinger** [comment]
Closed in https://github.com/aldettinger/camel-quarkus-workshop/pull/12, many thanks for inputs.

**Pull request closed without merging**
